/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.FormCadastroController;
import dao.UsuarioDAO;
import dao.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author USUARIO
 */
public class ticket extends javax.swing.JFrame {

    private final FormCadastroController controller;

    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
         controller = new FormCadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enviarticket = new javax.swing.JLabel();
        fundoazul = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        numerodecontato = new javax.swing.JLabel();
        Email2 = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        jTextFieldassunto = new javax.swing.JTextField();
        jTextFieldnumerodecontato = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadescricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        fundobranco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Envie seu Ticket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviarticket.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        enviarticket.setForeground(new java.awt.Color(255, 255, 255));
        enviarticket.setText("Enviar um ticket");
        getContentPane().add(enviarticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        fundoazul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue0517-4dfc85cb0200460ab717b101ac07888f.jpg"))); // NOI18N
        getContentPane().add(fundoazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -180, 1140, 320));

        Email.setText("Assunto*");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        numerodecontato.setText("Número de Contato");
        getContentPane().add(numerodecontato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        Email2.setText("Email*");
        getContentPane().add(Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        descricao.setText("Descrição*");
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));
        getContentPane().add(jTextFieldassunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 750, 40));

        jTextFieldnumerodecontato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumerodecontatoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldnumerodecontato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 750, 40));

        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 750, 40));

        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelar.setText("Cancelar\n");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 110, 40));

        jTextAreadescricao.setColumns(20);
        jTextAreadescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreadescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 750, 130));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 100, 40));

        fundobranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-color-solid-background-1920x1080.png"))); // NOI18N
        fundobranco.setText("jLabel1");
        getContentPane().add(fundobranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 950, 530));

        setSize(new java.awt.Dimension(1047, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     controller.salvaUsuario();
                                         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldnumerodecontatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumerodecontatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumerodecontatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    public JTextArea getjTextAreadescricao() {
        return jTextAreadescricao;
    }

    public void setjTextAreadescricao(JTextArea jTextAreadescricao) {
        this.jTextAreadescricao = jTextAreadescricao;
    }

    public JTextField getjTextFieldassunto() {
        return jTextFieldassunto;
    }

    public void setjTextFieldassunto(JTextField jTextFieldassunto) {
        this.jTextFieldassunto = jTextFieldassunto;
    }

    public JTextField getjTextFieldemail() {
        return jTextFieldemail;
    }

    public void setjTextFieldemail(JTextField jTextFieldemail) {
        this.jTextFieldemail = jTextFieldemail;
    }
    public JTextField getjTextFieldnumerodecontato() {
        return jTextFieldnumerodecontato;
    }

    public void setjTextFieldnumerodecontato(JTextField jTextFieldnumerodecontato) {
        this.jTextFieldnumerodecontato = jTextFieldnumerodecontato;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email2;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel enviarticket;
    private javax.swing.JLabel fundoazul;
    private javax.swing.JLabel fundobranco;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreadescricao;
    private javax.swing.JTextField jTextFieldassunto;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldnumerodecontato;
    private javax.swing.JLabel numerodecontato;
    // End of variables declaration//GEN-END:variables
}
